
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: system
rules:
- apiGroups:
  - operator.gatekeeper.sh
  resources:
  - gatekeepers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.gatekeeper.sh
  resources:
  - gatekeepers/status
  verbs:
  - get
  - patch
  - update
